//! Adobe Glyph List (AGL) glyph names, used to validate `/Differences` arrays
//! in non-symbolic TrueType fonts (Matterhorn 31-022, ISO 14289-1 7.21.6).
//!
//! Source: <https://github.com/adobe-type-tools/agl-aglfn> (glyphlist.txt),
//! Copyright 2002-2019 Adobe, BSD-3-Clause. Names are sorted bytewise so the
//! table can be searched with `binary_search`.

/// Returns true if `name` is a glyph name listed in the Adobe Glyph List.
///
/// Names of the form `uniXXXX`, `uXXXX[XX]`, `gNN`, `cidNN` are *not* in the AGL
/// proper; callers decide separately whether to accept them.
pub fn is_agl_name(name: &[u8]) -> bool {
    AGL_NAMES.binary_search_by(|probe| probe.as_bytes().cmp(name)).is_ok()
}

/// All 4281 glyph names of the Adobe Glyph List, sorted bytewise.
#[rustfmt::skip]
static AGL_NAMES: [&str; 4281] = [
    "A", "AE", "AEacute", "AEmacron", "AEsmall", "Aacute", "Aacutesmall", "Abreve", "Abreveacute",
    "Abrevecyrillic", "Abrevedotbelow", "Abrevegrave", "Abrevehookabove", "Abrevetilde", "Acaron",
    "Acircle", "Acircumflex", "Acircumflexacute", "Acircumflexdotbelow", "Acircumflexgrave",
    "Acircumflexhookabove", "Acircumflexsmall", "Acircumflextilde", "Acute", "Acutesmall",
    "Acyrillic", "Adblgrave", "Adieresis", "Adieresiscyrillic", "Adieresismacron", "Adieresissmall",
    "Adotbelow", "Adotmacron", "Agrave", "Agravesmall", "Ahookabove", "Aiecyrillic",
    "Ainvertedbreve", "Alpha", "Alphatonos", "Amacron", "Amonospace", "Aogonek", "Aring",
    "Aringacute", "Aringbelow", "Aringsmall", "Asmall", "Atilde", "Atildesmall", "Aybarmenian", "B",
    "Bcircle", "Bdotaccent", "Bdotbelow", "Becyrillic", "Benarmenian", "Beta", "Bhook",
    "Blinebelow", "Bmonospace", "Brevesmall", "Bsmall", "Btopbar", "C", "Caarmenian", "Cacute",
    "Caron", "Caronsmall", "Ccaron", "Ccedilla", "Ccedillaacute", "Ccedillasmall", "Ccircle",
    "Ccircumflex", "Cdot", "Cdotaccent", "Cedillasmall", "Chaarmenian", "Cheabkhasiancyrillic",
    "Checyrillic", "Chedescenderabkhasiancyrillic", "Chedescendercyrillic", "Chedieresiscyrillic",
    "Cheharmenian", "Chekhakassiancyrillic", "Cheverticalstrokecyrillic", "Chi", "Chook",
    "Circumflexsmall", "Cmonospace", "Coarmenian", "Csmall", "D", "DZ", "DZcaron", "Daarmenian",
    "Dafrican", "Dcaron", "Dcedilla", "Dcircle", "Dcircumflexbelow", "Dcroat", "Ddotaccent",
    "Ddotbelow", "Decyrillic", "Deicoptic", "Delta", "Deltagreek", "Dhook", "Dieresis",
    "DieresisAcute", "DieresisGrave", "Dieresissmall", "Digammagreek", "Djecyrillic", "Dlinebelow",
    "Dmonospace", "Dotaccentsmall", "Dslash", "Dsmall", "Dtopbar", "Dz", "Dzcaron",
    "Dzeabkhasiancyrillic", "Dzecyrillic", "Dzhecyrillic", "E", "Eacute", "Eacutesmall", "Ebreve",
    "Ecaron", "Ecedillabreve", "Echarmenian", "Ecircle", "Ecircumflex", "Ecircumflexacute",
    "Ecircumflexbelow", "Ecircumflexdotbelow", "Ecircumflexgrave", "Ecircumflexhookabove",
    "Ecircumflexsmall", "Ecircumflextilde", "Ecyrillic", "Edblgrave", "Edieresis", "Edieresissmall",
    "Edot", "Edotaccent", "Edotbelow", "Efcyrillic", "Egrave", "Egravesmall", "Eharmenian",
    "Ehookabove", "Eightroman", "Einvertedbreve", "Eiotifiedcyrillic", "Elcyrillic", "Elevenroman",
    "Emacron", "Emacronacute", "Emacrongrave", "Emcyrillic", "Emonospace", "Encyrillic",
    "Endescendercyrillic", "Eng", "Enghecyrillic", "Enhookcyrillic", "Eogonek", "Eopen", "Epsilon",
    "Epsilontonos", "Ercyrillic", "Ereversed", "Ereversedcyrillic", "Escyrillic",
    "Esdescendercyrillic", "Esh", "Esmall", "Eta", "Etarmenian", "Etatonos", "Eth", "Ethsmall",
    "Etilde", "Etildebelow", "Euro", "Ezh", "Ezhcaron", "Ezhreversed", "F", "Fcircle", "Fdotaccent",
    "Feharmenian", "Feicoptic", "Fhook", "Fitacyrillic", "Fiveroman", "Fmonospace", "Fourroman",
    "Fsmall", "G", "GBsquare", "Gacute", "Gamma", "Gammaafrican", "Gangiacoptic", "Gbreve",
    "Gcaron", "Gcedilla", "Gcircle", "Gcircumflex", "Gcommaaccent", "Gdot", "Gdotaccent",
    "Gecyrillic", "Ghadarmenian", "Ghemiddlehookcyrillic", "Ghestrokecyrillic", "Gheupturncyrillic",
    "Ghook", "Gimarmenian", "Gjecyrillic", "Gmacron", "Gmonospace", "Grave", "Gravesmall", "Gsmall",
    "Gsmallhook", "Gstroke", "H", "H18533", "H18543", "H18551", "H22073", "HPsquare",
    "Haabkhasiancyrillic", "Hadescendercyrillic", "Hardsigncyrillic", "Hbar", "Hbrevebelow",
    "Hcedilla", "Hcircle", "Hcircumflex", "Hdieresis", "Hdotaccent", "Hdotbelow", "Hmonospace",
    "Hoarmenian", "Horicoptic", "Hsmall", "Hungarumlaut", "Hungarumlautsmall", "Hzsquare", "I",
    "IAcyrillic", "IJ", "IUcyrillic", "Iacute", "Iacutesmall", "Ibreve", "Icaron", "Icircle",
    "Icircumflex", "Icircumflexsmall", "Icyrillic", "Idblgrave", "Idieresis", "Idieresisacute",
    "Idieresiscyrillic", "Idieresissmall", "Idot", "Idotaccent", "Idotbelow", "Iebrevecyrillic",
    "Iecyrillic", "Ifraktur", "Igrave", "Igravesmall", "Ihookabove", "Iicyrillic", "Iinvertedbreve",
    "Iishortcyrillic", "Imacron", "Imacroncyrillic", "Imonospace", "Iniarmenian", "Iocyrillic",
    "Iogonek", "Iota", "Iotaafrican", "Iotadieresis", "Iotatonos", "Ismall", "Istroke", "Itilde",
    "Itildebelow", "Izhitsacyrillic", "Izhitsadblgravecyrillic", "J", "Jaarmenian", "Jcircle",
    "Jcircumflex", "Jecyrillic", "Jheharmenian", "Jmonospace", "Jsmall", "K", "KBsquare",
    "KKsquare", "Kabashkircyrillic", "Kacute", "Kacyrillic", "Kadescendercyrillic",
    "Kahookcyrillic", "Kappa", "Kastrokecyrillic", "Kaverticalstrokecyrillic", "Kcaron", "Kcedilla",
    "Kcircle", "Kcommaaccent", "Kdotbelow", "Keharmenian", "Kenarmenian", "Khacyrillic",
    "Kheicoptic", "Khook", "Kjecyrillic", "Klinebelow", "Kmonospace", "Koppacyrillic", "Koppagreek",
    "Ksicyrillic", "Ksmall", "L", "LJ", "LL", "Lacute", "Lambda", "Lcaron", "Lcedilla", "Lcircle",
    "Lcircumflexbelow", "Lcommaaccent", "Ldot", "Ldotaccent", "Ldotbelow", "Ldotbelowmacron",
    "Liwnarmenian", "Lj", "Ljecyrillic", "Llinebelow", "Lmonospace", "Lslash", "Lslashsmall",
    "Lsmall", "M", "MBsquare", "Macron", "Macronsmall", "Macute", "Mcircle", "Mdotaccent",
    "Mdotbelow", "Menarmenian", "Mmonospace", "Msmall", "Mturned", "Mu", "N", "NJ", "Nacute",
    "Ncaron", "Ncedilla", "Ncircle", "Ncircumflexbelow", "Ncommaaccent", "Ndotaccent", "Ndotbelow",
    "Nhookleft", "Nineroman", "Nj", "Njecyrillic", "Nlinebelow", "Nmonospace", "Nowarmenian",
    "Nsmall", "Ntilde", "Ntildesmall", "Nu", "O", "OE", "OEsmall", "Oacute", "Oacutesmall",
    "Obarredcyrillic", "Obarreddieresiscyrillic", "Obreve", "Ocaron", "Ocenteredtilde", "Ocircle",
    "Ocircumflex", "Ocircumflexacute", "Ocircumflexdotbelow", "Ocircumflexgrave",
    "Ocircumflexhookabove", "Ocircumflexsmall", "Ocircumflextilde", "Ocyrillic", "Odblacute",
    "Odblgrave", "Odieresis", "Odieresiscyrillic", "Odieresissmall", "Odotbelow", "Ogoneksmall",
    "Ograve", "Ogravesmall", "Oharmenian", "Ohm", "Ohookabove", "Ohorn", "Ohornacute",
    "Ohorndotbelow", "Ohorngrave", "Ohornhookabove", "Ohorntilde", "Ohungarumlaut", "Oi",
    "Oinvertedbreve", "Omacron", "Omacronacute", "Omacrongrave", "Omega", "Omegacyrillic",
    "Omegagreek", "Omegaroundcyrillic", "Omegatitlocyrillic", "Omegatonos", "Omicron",
    "Omicrontonos", "Omonospace", "Oneroman", "Oogonek", "Oogonekmacron", "Oopen", "Oslash",
    "Oslashacute", "Oslashsmall", "Osmall", "Ostrokeacute", "Otcyrillic", "Otilde", "Otildeacute",
    "Otildedieresis", "Otildesmall", "P", "Pacute", "Pcircle", "Pdotaccent", "Pecyrillic",
    "Peharmenian", "Pemiddlehookcyrillic", "Phi", "Phook", "Pi", "Piwrarmenian", "Pmonospace",
    "Psi", "Psicyrillic", "Psmall", "Q", "Qcircle", "Qmonospace", "Qsmall", "R", "Raarmenian",
    "Racute", "Rcaron", "Rcedilla", "Rcircle", "Rcommaaccent", "Rdblgrave", "Rdotaccent",
    "Rdotbelow", "Rdotbelowmacron", "Reharmenian", "Rfraktur", "Rho", "Ringsmall", "Rinvertedbreve",
    "Rlinebelow", "Rmonospace", "Rsmall", "Rsmallinverted", "Rsmallinvertedsuperior", "S",
    "SF010000", "SF020000", "SF030000", "SF040000", "SF050000", "SF060000", "SF070000", "SF080000",
    "SF090000", "SF100000", "SF110000", "SF190000", "SF200000", "SF210000", "SF220000", "SF230000",
    "SF240000", "SF250000", "SF260000", "SF270000", "SF280000", "SF360000", "SF370000", "SF380000",
    "SF390000", "SF400000", "SF410000", "SF420000", "SF430000", "SF440000", "SF450000", "SF460000",
    "SF470000", "SF480000", "SF490000", "SF500000", "SF510000", "SF520000", "SF530000", "SF540000",
    "Sacute", "Sacutedotaccent", "Sampigreek", "Scaron", "Scarondotaccent", "Scaronsmall",
    "Scedilla", "Schwa", "Schwacyrillic", "Schwadieresiscyrillic", "Scircle", "Scircumflex",
    "Scommaaccent", "Sdotaccent", "Sdotbelow", "Sdotbelowdotaccent", "Seharmenian", "Sevenroman",
    "Shaarmenian", "Shacyrillic", "Shchacyrillic", "Sheicoptic", "Shhacyrillic", "Shimacoptic",
    "Sigma", "Sixroman", "Smonospace", "Softsigncyrillic", "Ssmall", "Stigmagreek", "T", "Tau",
    "Tbar", "Tcaron", "Tcedilla", "Tcircle", "Tcircumflexbelow", "Tcommaaccent", "Tdotaccent",
    "Tdotbelow", "Tecyrillic", "Tedescendercyrillic", "Tenroman", "Tetsecyrillic", "Theta", "Thook",
    "Thorn", "Thornsmall", "Threeroman", "Tildesmall", "Tiwnarmenian", "Tlinebelow", "Tmonospace",
    "Toarmenian", "Tonefive", "Tonesix", "Tonetwo", "Tretroflexhook", "Tsecyrillic", "Tshecyrillic",
    "Tsmall", "Twelveroman", "Tworoman", "U", "Uacute", "Uacutesmall", "Ubreve", "Ucaron",
    "Ucircle", "Ucircumflex", "Ucircumflexbelow", "Ucircumflexsmall", "Ucyrillic", "Udblacute",
    "Udblgrave", "Udieresis", "Udieresisacute", "Udieresisbelow", "Udieresiscaron",
    "Udieresiscyrillic", "Udieresisgrave", "Udieresismacron", "Udieresissmall", "Udotbelow",
    "Ugrave", "Ugravesmall", "Uhookabove", "Uhorn", "Uhornacute", "Uhorndotbelow", "Uhorngrave",
    "Uhornhookabove", "Uhorntilde", "Uhungarumlaut", "Uhungarumlautcyrillic", "Uinvertedbreve",
    "Ukcyrillic", "Umacron", "Umacroncyrillic", "Umacrondieresis", "Umonospace", "Uogonek",
    "Upsilon", "Upsilon1", "Upsilonacutehooksymbolgreek", "Upsilonafrican", "Upsilondieresis",
    "Upsilondieresishooksymbolgreek", "Upsilonhooksymbol", "Upsilontonos", "Uring",
    "Ushortcyrillic", "Usmall", "Ustraightcyrillic", "Ustraightstrokecyrillic", "Utilde",
    "Utildeacute", "Utildebelow", "V", "Vcircle", "Vdotbelow", "Vecyrillic", "Vewarmenian", "Vhook",
    "Vmonospace", "Voarmenian", "Vsmall", "Vtilde", "W", "Wacute", "Wcircle", "Wcircumflex",
    "Wdieresis", "Wdotaccent", "Wdotbelow", "Wgrave", "Wmonospace", "Wsmall", "X", "Xcircle",
    "Xdieresis", "Xdotaccent", "Xeharmenian", "Xi", "Xmonospace", "Xsmall", "Y", "Yacute",
    "Yacutesmall", "Yatcyrillic", "Ycircle", "Ycircumflex", "Ydieresis", "Ydieresissmall",
    "Ydotaccent", "Ydotbelow", "Yericyrillic", "Yerudieresiscyrillic", "Ygrave", "Yhook",
    "Yhookabove", "Yiarmenian", "Yicyrillic", "Yiwnarmenian", "Ymonospace", "Ysmall", "Ytilde",
    "Yusbigcyrillic", "Yusbigiotifiedcyrillic", "Yuslittlecyrillic", "Yuslittleiotifiedcyrillic",
    "Z", "Zaarmenian", "Zacute", "Zcaron", "Zcaronsmall", "Zcircle", "Zcircumflex", "Zdot",
    "Zdotaccent", "Zdotbelow", "Zecyrillic", "Zedescendercyrillic", "Zedieresiscyrillic", "Zeta",
    "Zhearmenian", "Zhebrevecyrillic", "Zhecyrillic", "Zhedescendercyrillic", "Zhedieresiscyrillic",
    "Zlinebelow", "Zmonospace", "Zsmall", "Zstroke", "a", "aabengali", "aacute", "aadeva",
    "aagujarati", "aagurmukhi", "aamatragurmukhi", "aarusquare", "aavowelsignbengali",
    "aavowelsigndeva", "aavowelsigngujarati", "abbreviationmarkarmenian", "abbreviationsigndeva",
    "abengali", "abopomofo", "abreve", "abreveacute", "abrevecyrillic", "abrevedotbelow",
    "abrevegrave", "abrevehookabove", "abrevetilde", "acaron", "acircle", "acircumflex",
    "acircumflexacute", "acircumflexdotbelow", "acircumflexgrave", "acircumflexhookabove",
    "acircumflextilde", "acute", "acutebelowcmb", "acutecmb", "acutecomb", "acutedeva",
    "acutelowmod", "acutetonecmb", "acyrillic", "adblgrave", "addakgurmukhi", "adeva", "adieresis",
    "adieresiscyrillic", "adieresismacron", "adotbelow", "adotmacron", "ae", "aeacute", "aekorean",
    "aemacron", "afii00208", "afii08941", "afii10017", "afii10018", "afii10019", "afii10020",
    "afii10021", "afii10022", "afii10023", "afii10024", "afii10025", "afii10026", "afii10027",
    "afii10028", "afii10029", "afii10030", "afii10031", "afii10032", "afii10033", "afii10034",
    "afii10035", "afii10036", "afii10037", "afii10038", "afii10039", "afii10040", "afii10041",
    "afii10042", "afii10043", "afii10044", "afii10045", "afii10046", "afii10047", "afii10048",
    "afii10049", "afii10050", "afii10051", "afii10052", "afii10053", "afii10054", "afii10055",
    "afii10056", "afii10057", "afii10058", "afii10059", "afii10060", "afii10061", "afii10062",
    "afii10063", "afii10064", "afii10065", "afii10066", "afii10067", "afii10068", "afii10069",
    "afii10070", "afii10071", "afii10072", "afii10073", "afii10074", "afii10075", "afii10076",
    "afii10077", "afii10078", "afii10079", "afii10080", "afii10081", "afii10082", "afii10083",
    "afii10084", "afii10085", "afii10086", "afii10087", "afii10088", "afii10089", "afii10090",
    "afii10091", "afii10092", "afii10093", "afii10094", "afii10095", "afii10096", "afii10097",
    "afii10098", "afii10099", "afii10100", "afii10101", "afii10102", "afii10103", "afii10104",
    "afii10105", "afii10106", "afii10107", "afii10108", "afii10109", "afii10110", "afii10145",
    "afii10146", "afii10147", "afii10148", "afii10192", "afii10193", "afii10194", "afii10195",
    "afii10196", "afii10831", "afii10832", "afii10846", "afii299", "afii300", "afii301",
    "afii57381", "afii57388", "afii57392", "afii57393", "afii57394", "afii57395", "afii57396",
    "afii57397", "afii57398", "afii57399", "afii57400", "afii57401", "afii57403", "afii57407",
    "afii57409", "afii57410", "afii57411", "afii57412", "afii57413", "afii57414", "afii57415",
    "afii57416", "afii57417", "afii57418", "afii57419", "afii57420", "afii57421", "afii57422",
    "afii57423", "afii57424", "afii57425", "afii57426", "afii57427", "afii57428", "afii57429",
    "afii57430", "afii57431", "afii57432", "afii57433", "afii57434", "afii57440", "afii57441",
    "afii57442", "afii57443", "afii57444", "afii57445", "afii57446", "afii57448", "afii57449",
    "afii57450", "afii57451", "afii57452", "afii57453", "afii57454", "afii57455", "afii57456",
    "afii57457", "afii57458", "afii57470", "afii57505", "afii57506", "afii57507", "afii57508",
    "afii57509", "afii57511", "afii57512", "afii57513", "afii57514", "afii57519", "afii57534",
    "afii57636", "afii57645", "afii57658", "afii57664", "afii57665", "afii57666", "afii57667",
    "afii57668", "afii57669", "afii57670", "afii57671", "afii57672", "afii57673", "afii57674",
    "afii57675", "afii57676", "afii57677", "afii57678", "afii57679", "afii57680", "afii57681",
    "afii57682", "afii57683", "afii57684", "afii57685", "afii57686", "afii57687", "afii57688",
    "afii57689", "afii57690", "afii57694", "afii57695", "afii57700", "afii57705", "afii57716",
    "afii57717", "afii57718", "afii57723", "afii57793", "afii57794", "afii57795", "afii57796",
    "afii57797", "afii57798", "afii57799", "afii57800", "afii57801", "afii57802", "afii57803",
    "afii57804", "afii57806", "afii57807", "afii57839", "afii57841", "afii57842", "afii57929",
    "afii61248", "afii61289", "afii61352", "afii61573", "afii61574", "afii61575", "afii61664",
    "afii63167", "afii64937", "agrave", "agujarati", "agurmukhi", "ahiragana", "ahookabove",
    "aibengali", "aibopomofo", "aideva", "aiecyrillic", "aigujarati", "aigurmukhi",
    "aimatragurmukhi", "ainarabic", "ainfinalarabic", "aininitialarabic", "ainmedialarabic",
    "ainvertedbreve", "aivowelsignbengali", "aivowelsigndeva", "aivowelsigngujarati", "akatakana",
    "akatakanahalfwidth", "akorean", "alef", "alefarabic", "alefdageshhebrew", "aleffinalarabic",
    "alefhamzaabovearabic", "alefhamzaabovefinalarabic", "alefhamzabelowarabic",
    "alefhamzabelowfinalarabic", "alefhebrew", "aleflamedhebrew", "alefmaddaabovearabic",
    "alefmaddaabovefinalarabic", "alefmaksuraarabic", "alefmaksurafinalarabic",
    "alefmaksurainitialarabic", "alefmaksuramedialarabic", "alefpatahhebrew", "alefqamatshebrew",
    "aleph", "allequal", "alpha", "alphatonos", "amacron", "amonospace", "ampersand",
    "ampersandmonospace", "ampersandsmall", "amsquare", "anbopomofo", "angbopomofo",
    "angkhankhuthai", "angle", "anglebracketleft", "anglebracketleftvertical", "anglebracketright",
    "anglebracketrightvertical", "angleleft", "angleright", "angstrom", "anoteleia", "anudattadeva",
    "anusvarabengali", "anusvaradeva", "anusvaragujarati", "aogonek", "apaatosquare", "aparen",
    "apostrophearmenian", "apostrophemod", "apple", "approaches", "approxequal",
    "approxequalorimage", "approximatelyequal", "araeaekorean", "araeakorean", "arc",
    "arighthalfring", "aring", "aringacute", "aringbelow", "arrowboth", "arrowdashdown",
    "arrowdashleft", "arrowdashright", "arrowdashup", "arrowdblboth", "arrowdbldown",
    "arrowdblleft", "arrowdblright", "arrowdblup", "arrowdown", "arrowdownleft", "arrowdownright",
    "arrowdownwhite", "arrowheaddownmod", "arrowheadleftmod", "arrowheadrightmod", "arrowheadupmod",
    "arrowhorizex", "arrowleft", "arrowleftdbl", "arrowleftdblstroke", "arrowleftoverright",
    "arrowleftwhite", "arrowright", "arrowrightdblstroke", "arrowrightheavy", "arrowrightoverleft",
    "arrowrightwhite", "arrowtableft", "arrowtabright", "arrowup", "arrowupdn", "arrowupdnbse",
    "arrowupdownbase", "arrowupleft", "arrowupleftofdown", "arrowupright", "arrowupwhite",
    "arrowvertex", "asciicircum", "asciicircummonospace", "asciitilde", "asciitildemonospace",
    "ascript", "ascriptturned", "asmallhiragana", "asmallkatakana", "asmallkatakanahalfwidth",
    "asterisk", "asteriskaltonearabic", "asteriskarabic", "asteriskmath", "asteriskmonospace",
    "asterisksmall", "asterism", "asuperior", "asymptoticallyequal", "at", "atilde", "atmonospace",
    "atsmall", "aturned", "aubengali", "aubopomofo", "audeva", "augujarati", "augurmukhi",
    "aulengthmarkbengali", "aumatragurmukhi", "auvowelsignbengali", "auvowelsigndeva",
    "auvowelsigngujarati", "avagrahadeva", "aybarmenian", "ayin", "ayinaltonehebrew", "ayinhebrew",
    "b", "babengali", "backslash", "backslashmonospace", "badeva", "bagujarati", "bagurmukhi",
    "bahiragana", "bahtthai", "bakatakana", "bar", "barmonospace", "bbopomofo", "bcircle",
    "bdotaccent", "bdotbelow", "beamedsixteenthnotes", "because", "becyrillic", "beharabic",
    "behfinalarabic", "behinitialarabic", "behiragana", "behmedialarabic", "behmeeminitialarabic",
    "behmeemisolatedarabic", "behnoonfinalarabic", "bekatakana", "benarmenian", "bet", "beta",
    "betasymbolgreek", "betdagesh", "betdageshhebrew", "bethebrew", "betrafehebrew", "bhabengali",
    "bhadeva", "bhagujarati", "bhagurmukhi", "bhook", "bihiragana", "bikatakana", "bilabialclick",
    "bindigurmukhi", "birusquare", "blackcircle", "blackdiamond", "blackdownpointingtriangle",
    "blackleftpointingpointer", "blackleftpointingtriangle", "blacklenticularbracketleft",
    "blacklenticularbracketleftvertical", "blacklenticularbracketright",
    "blacklenticularbracketrightvertical", "blacklowerlefttriangle", "blacklowerrighttriangle",
    "blackrectangle", "blackrightpointingpointer", "blackrightpointingtriangle", "blacksmallsquare",
    "blacksmilingface", "blacksquare", "blackstar", "blackupperlefttriangle",
    "blackupperrighttriangle", "blackuppointingsmalltriangle", "blackuppointingtriangle", "blank",
    "blinebelow", "block", "bmonospace", "bobaimaithai", "bohiragana", "bokatakana", "bparen",
    "bqsquare", "braceex", "braceleft", "braceleftbt", "braceleftmid", "braceleftmonospace",
    "braceleftsmall", "bracelefttp", "braceleftvertical", "braceright", "bracerightbt",
    "bracerightmid", "bracerightmonospace", "bracerightsmall", "bracerighttp", "bracerightvertical",
    "bracketleft", "bracketleftbt", "bracketleftex", "bracketleftmonospace", "bracketlefttp",
    "bracketright", "bracketrightbt", "bracketrightex", "bracketrightmonospace", "bracketrighttp",
    "breve", "brevebelowcmb", "brevecmb", "breveinvertedbelowcmb", "breveinvertedcmb",
    "breveinverteddoublecmb", "bridgebelowcmb", "bridgeinvertedbelowcmb", "brokenbar", "bstroke",
    "bsuperior", "btopbar", "buhiragana", "bukatakana", "bullet", "bulletinverse", "bulletoperator",
    "bullseye", "c", "caarmenian", "cabengali", "cacute", "cadeva", "cagujarati", "cagurmukhi",
    "calsquare", "candrabindubengali", "candrabinducmb", "candrabindudeva", "candrabindugujarati",
    "capslock", "careof", "caron", "caronbelowcmb", "caroncmb", "carriagereturn", "cbopomofo",
    "ccaron", "ccedilla", "ccedillaacute", "ccircle", "ccircumflex", "ccurl", "cdot", "cdotaccent",
    "cdsquare", "cedilla", "cedillacmb", "cent", "centigrade", "centinferior", "centmonospace",
    "centoldstyle", "centsuperior", "chaarmenian", "chabengali", "chadeva", "chagujarati",
    "chagurmukhi", "chbopomofo", "cheabkhasiancyrillic", "checkmark", "checyrillic",
    "chedescenderabkhasiancyrillic", "chedescendercyrillic", "chedieresiscyrillic", "cheharmenian",
    "chekhakassiancyrillic", "cheverticalstrokecyrillic", "chi", "chieuchacirclekorean",
    "chieuchaparenkorean", "chieuchcirclekorean", "chieuchkorean", "chieuchparenkorean",
    "chochangthai", "chochanthai", "chochingthai", "chochoethai", "chook", "cieucacirclekorean",
    "cieucaparenkorean", "cieuccirclekorean", "cieuckorean", "cieucparenkorean",
    "cieucuparenkorean", "circle", "circlemultiply", "circleot", "circleplus", "circlepostalmark",
    "circlewithlefthalfblack", "circlewithrighthalfblack", "circumflex", "circumflexbelowcmb",
    "circumflexcmb", "clear", "clickalveolar", "clickdental", "clicklateral", "clickretroflex",
    "club", "clubsuitblack", "clubsuitwhite", "cmcubedsquare", "cmonospace", "cmsquaredsquare",
    "coarmenian", "colon", "colonmonetary", "colonmonospace", "colonsign", "colonsmall",
    "colontriangularhalfmod", "colontriangularmod", "comma", "commaabovecmb", "commaaboverightcmb",
    "commaaccent", "commaarabic", "commaarmenian", "commainferior", "commamonospace",
    "commareversedabovecmb", "commareversedmod", "commasmall", "commasuperior",
    "commaturnedabovecmb", "commaturnedmod", "compass", "congruent", "contourintegral", "control",
    "controlACK", "controlBEL", "controlBS", "controlCAN", "controlCR", "controlDC1", "controlDC2",
    "controlDC3", "controlDC4", "controlDEL", "controlDLE", "controlEM", "controlENQ", "controlEOT",
    "controlESC", "controlETB", "controlETX", "controlFF", "controlFS", "controlGS", "controlHT",
    "controlLF", "controlNAK", "controlRS", "controlSI", "controlSO", "controlSOT", "controlSTX",
    "controlSUB", "controlSYN", "controlUS", "controlVT", "copyright", "copyrightsans",
    "copyrightserif", "cornerbracketleft", "cornerbracketlefthalfwidth",
    "cornerbracketleftvertical", "cornerbracketright", "cornerbracketrighthalfwidth",
    "cornerbracketrightvertical", "corporationsquare", "cosquare", "coverkgsquare", "cparen",
    "cruzeiro", "cstretched", "curlyand", "curlyor", "currency", "cyrBreve", "cyrFlex", "cyrbreve",
    "cyrflex", "d", "daarmenian", "dabengali", "dadarabic", "dadeva", "dadfinalarabic",
    "dadinitialarabic", "dadmedialarabic", "dagesh", "dageshhebrew", "dagger", "daggerdbl",
    "dagujarati", "dagurmukhi", "dahiragana", "dakatakana", "dalarabic", "dalet", "daletdagesh",
    "daletdageshhebrew", "dalethatafpatah", "dalethatafpatahhebrew", "dalethatafsegol",
    "dalethatafsegolhebrew", "dalethebrew", "dalethiriq", "dalethiriqhebrew", "daletholam",
    "daletholamhebrew", "daletpatah", "daletpatahhebrew", "daletqamats", "daletqamatshebrew",
    "daletqubuts", "daletqubutshebrew", "daletsegol", "daletsegolhebrew", "daletsheva",
    "daletshevahebrew", "dalettsere", "dalettserehebrew", "dalfinalarabic", "dammaarabic",
    "dammalowarabic", "dammatanaltonearabic", "dammatanarabic", "danda", "dargahebrew",
    "dargalefthebrew", "dasiapneumatacyrilliccmb", "dblGrave", "dblanglebracketleft",
    "dblanglebracketleftvertical", "dblanglebracketright", "dblanglebracketrightvertical",
    "dblarchinvertedbelowcmb", "dblarrowleft", "dblarrowright", "dbldanda", "dblgrave",
    "dblgravecmb", "dblintegral", "dbllowline", "dbllowlinecmb", "dbloverlinecmb", "dblprimemod",
    "dblverticalbar", "dblverticallineabovecmb", "dbopomofo", "dbsquare", "dcaron", "dcedilla",
    "dcircle", "dcircumflexbelow", "dcroat", "ddabengali", "ddadeva", "ddagujarati", "ddagurmukhi",
    "ddalarabic", "ddalfinalarabic", "dddhadeva", "ddhabengali", "ddhadeva", "ddhagujarati",
    "ddhagurmukhi", "ddotaccent", "ddotbelow", "decimalseparatorarabic", "decimalseparatorpersian",
    "decyrillic", "degree", "dehihebrew", "dehiragana", "deicoptic", "dekatakana", "deleteleft",
    "deleteright", "delta", "deltaturned", "denominatorminusonenumeratorbengali", "dezh",
    "dhabengali", "dhadeva", "dhagujarati", "dhagurmukhi", "dhook", "dialytikatonos",
    "dialytikatonoscmb", "diamond", "diamondsuitwhite", "dieresis", "dieresisacute",
    "dieresisbelowcmb", "dieresiscmb", "dieresisgrave", "dieresistonos", "dihiragana", "dikatakana",
    "dittomark", "divide", "divides", "divisionslash", "djecyrillic", "dkshade", "dlinebelow",
    "dlsquare", "dmacron", "dmonospace", "dnblock", "dochadathai", "dodekthai", "dohiragana",
    "dokatakana", "dollar", "dollarinferior", "dollarmonospace", "dollaroldstyle", "dollarsmall",
    "dollarsuperior", "dong", "dorusquare", "dotaccent", "dotaccentcmb", "dotbelowcmb",
    "dotbelowcomb", "dotkatakana", "dotlessi", "dotlessj", "dotlessjstrokehook", "dotmath",
    "dottedcircle", "doubleyodpatah", "doubleyodpatahhebrew", "downtackbelowcmb", "downtackmod",
    "dparen", "dsuperior", "dtail", "dtopbar", "duhiragana", "dukatakana", "dz", "dzaltone",
    "dzcaron", "dzcurl", "dzeabkhasiancyrillic", "dzecyrillic", "dzhecyrillic", "e", "eacute",
    "earth", "ebengali", "ebopomofo", "ebreve", "ecandradeva", "ecandragujarati",
    "ecandravowelsigndeva", "ecandravowelsigngujarati", "ecaron", "ecedillabreve", "echarmenian",
    "echyiwnarmenian", "ecircle", "ecircumflex", "ecircumflexacute", "ecircumflexbelow",
    "ecircumflexdotbelow", "ecircumflexgrave", "ecircumflexhookabove", "ecircumflextilde",
    "ecyrillic", "edblgrave", "edeva", "edieresis", "edot", "edotaccent", "edotbelow", "eegurmukhi",
    "eematragurmukhi", "efcyrillic", "egrave", "egujarati", "eharmenian", "ehbopomofo", "ehiragana",
    "ehookabove", "eibopomofo", "eight", "eightarabic", "eightbengali", "eightcircle",
    "eightcircleinversesansserif", "eightdeva", "eighteencircle", "eighteenparen", "eighteenperiod",
    "eightgujarati", "eightgurmukhi", "eighthackarabic", "eighthangzhou", "eighthnotebeamed",
    "eightideographicparen", "eightinferior", "eightmonospace", "eightoldstyle", "eightparen",
    "eightperiod", "eightpersian", "eightroman", "eightsuperior", "eightthai", "einvertedbreve",
    "eiotifiedcyrillic", "ekatakana", "ekatakanahalfwidth", "ekonkargurmukhi", "ekorean",
    "elcyrillic", "element", "elevencircle", "elevenparen", "elevenperiod", "elevenroman",
    "ellipsis", "ellipsisvertical", "emacron", "emacronacute", "emacrongrave", "emcyrillic",
    "emdash", "emdashvertical", "emonospace", "emphasismarkarmenian", "emptyset", "enbopomofo",
    "encyrillic", "endash", "endashvertical", "endescendercyrillic", "eng", "engbopomofo",
    "enghecyrillic", "enhookcyrillic", "enspace", "eogonek", "eokorean", "eopen", "eopenclosed",
    "eopenreversed", "eopenreversedclosed", "eopenreversedhook", "eparen", "epsilon",
    "epsilontonos", "equal", "equalmonospace", "equalsmall", "equalsuperior", "equivalence",
    "erbopomofo", "ercyrillic", "ereversed", "ereversedcyrillic", "escyrillic",
    "esdescendercyrillic", "esh", "eshcurl", "eshortdeva", "eshortvowelsigndeva", "eshreversedloop",
    "eshsquatreversed", "esmallhiragana", "esmallkatakana", "esmallkatakanahalfwidth", "estimated",
    "esuperior", "eta", "etarmenian", "etatonos", "eth", "etilde", "etildebelow",
    "etnahtafoukhhebrew", "etnahtafoukhlefthebrew", "etnahtahebrew", "etnahtalefthebrew", "eturned",
    "eukorean", "euro", "evowelsignbengali", "evowelsigndeva", "evowelsigngujarati", "exclam",
    "exclamarmenian", "exclamdbl", "exclamdown", "exclamdownsmall", "exclammonospace",
    "exclamsmall", "existential", "ezh", "ezhcaron", "ezhcurl", "ezhreversed", "ezhtail", "f",
    "fadeva", "fagurmukhi", "fahrenheit", "fathaarabic", "fathalowarabic", "fathatanarabic",
    "fbopomofo", "fcircle", "fdotaccent", "feharabic", "feharmenian", "fehfinalarabic",
    "fehinitialarabic", "fehmedialarabic", "feicoptic", "female", "ff", "ffi", "ffl", "fi",
    "fifteencircle", "fifteenparen", "fifteenperiod", "figuredash", "filledbox", "filledrect",
    "finalkaf", "finalkafdagesh", "finalkafdageshhebrew", "finalkafhebrew", "finalkafqamats",
    "finalkafqamatshebrew", "finalkafsheva", "finalkafshevahebrew", "finalmem", "finalmemhebrew",
    "finalnun", "finalnunhebrew", "finalpe", "finalpehebrew", "finaltsadi", "finaltsadihebrew",
    "firsttonechinese", "fisheye", "fitacyrillic", "five", "fivearabic", "fivebengali",
    "fivecircle", "fivecircleinversesansserif", "fivedeva", "fiveeighths", "fivegujarati",
    "fivegurmukhi", "fivehackarabic", "fivehangzhou", "fiveideographicparen", "fiveinferior",
    "fivemonospace", "fiveoldstyle", "fiveparen", "fiveperiod", "fivepersian", "fiveroman",
    "fivesuperior", "fivethai", "fl", "florin", "fmonospace", "fmsquare", "fofanthai", "fofathai",
    "fongmanthai", "forall", "four", "fourarabic", "fourbengali", "fourcircle",
    "fourcircleinversesansserif", "fourdeva", "fourgujarati", "fourgurmukhi", "fourhackarabic",
    "fourhangzhou", "fourideographicparen", "fourinferior", "fourmonospace", "fournumeratorbengali",
    "fouroldstyle", "fourparen", "fourperiod", "fourpersian", "fourroman", "foursuperior",
    "fourteencircle", "fourteenparen", "fourteenperiod", "fourthai", "fourthtonechinese", "fparen",
    "fraction", "franc", "g", "gabengali", "gacute", "gadeva", "gafarabic", "gaffinalarabic",
    "gafinitialarabic", "gafmedialarabic", "gagujarati", "gagurmukhi", "gahiragana", "gakatakana",
    "gamma", "gammalatinsmall", "gammasuperior", "gangiacoptic", "gbopomofo", "gbreve", "gcaron",
    "gcedilla", "gcircle", "gcircumflex", "gcommaaccent", "gdot", "gdotaccent", "gecyrillic",
    "gehiragana", "gekatakana", "geometricallyequal", "gereshaccenthebrew", "gereshhebrew",
    "gereshmuqdamhebrew", "germandbls", "gershayimaccenthebrew", "gershayimhebrew", "getamark",
    "ghabengali", "ghadarmenian", "ghadeva", "ghagujarati", "ghagurmukhi", "ghainarabic",
    "ghainfinalarabic", "ghaininitialarabic", "ghainmedialarabic", "ghemiddlehookcyrillic",
    "ghestrokecyrillic", "gheupturncyrillic", "ghhadeva", "ghhagurmukhi", "ghook", "ghzsquare",
    "gihiragana", "gikatakana", "gimarmenian", "gimel", "gimeldagesh", "gimeldageshhebrew",
    "gimelhebrew", "gjecyrillic", "glottalinvertedstroke", "glottalstop", "glottalstopinverted",
    "glottalstopmod", "glottalstopreversed", "glottalstopreversedmod",
    "glottalstopreversedsuperior", "glottalstopstroke", "glottalstopstrokereversed", "gmacron",
    "gmonospace", "gohiragana", "gokatakana", "gparen", "gpasquare", "gradient", "grave",
    "gravebelowcmb", "gravecmb", "gravecomb", "gravedeva", "gravelowmod", "gravemonospace",
    "gravetonecmb", "greater", "greaterequal", "greaterequalorless", "greatermonospace",
    "greaterorequivalent", "greaterorless", "greateroverequal", "greatersmall", "gscript",
    "gstroke", "guhiragana", "guillemotleft", "guillemotright", "guilsinglleft", "guilsinglright",
    "gukatakana", "guramusquare", "gysquare", "h", "haabkhasiancyrillic", "haaltonearabic",
    "habengali", "hadescendercyrillic", "hadeva", "hagujarati", "hagurmukhi", "haharabic",
    "hahfinalarabic", "hahinitialarabic", "hahiragana", "hahmedialarabic", "haitusquare",
    "hakatakana", "hakatakanahalfwidth", "halantgurmukhi", "hamzaarabic", "hamzadammaarabic",
    "hamzadammatanarabic", "hamzafathaarabic", "hamzafathatanarabic", "hamzalowarabic",
    "hamzalowkasraarabic", "hamzalowkasratanarabic", "hamzasukunarabic", "hangulfiller",
    "hardsigncyrillic", "harpoonleftbarbup", "harpoonrightbarbup", "hasquare", "hatafpatah",
    "hatafpatah16", "hatafpatah23", "hatafpatah2f", "hatafpatahhebrew", "hatafpatahnarrowhebrew",
    "hatafpatahquarterhebrew", "hatafpatahwidehebrew", "hatafqamats", "hatafqamats1b",
    "hatafqamats28", "hatafqamats34", "hatafqamatshebrew", "hatafqamatsnarrowhebrew",
    "hatafqamatsquarterhebrew", "hatafqamatswidehebrew", "hatafsegol", "hatafsegol17",
    "hatafsegol24", "hatafsegol30", "hatafsegolhebrew", "hatafsegolnarrowhebrew",
    "hatafsegolquarterhebrew", "hatafsegolwidehebrew", "hbar", "hbopomofo", "hbrevebelow",
    "hcedilla", "hcircle", "hcircumflex", "hdieresis", "hdotaccent", "hdotbelow", "he", "heart",
    "heartsuitblack", "heartsuitwhite", "hedagesh", "hedageshhebrew", "hehaltonearabic",
    "heharabic", "hehebrew", "hehfinalaltonearabic", "hehfinalalttwoarabic", "hehfinalarabic",
    "hehhamzaabovefinalarabic", "hehhamzaaboveisolatedarabic", "hehinitialaltonearabic",
    "hehinitialarabic", "hehiragana", "hehmedialaltonearabic", "hehmedialarabic", "heiseierasquare",
    "hekatakana", "hekatakanahalfwidth", "hekutaarusquare", "henghook", "herutusquare", "het",
    "hethebrew", "hhook", "hhooksuperior", "hieuhacirclekorean", "hieuhaparenkorean",
    "hieuhcirclekorean", "hieuhkorean", "hieuhparenkorean", "hihiragana", "hikatakana",
    "hikatakanahalfwidth", "hiriq", "hiriq14", "hiriq21", "hiriq2d", "hiriqhebrew",
    "hiriqnarrowhebrew", "hiriqquarterhebrew", "hiriqwidehebrew", "hlinebelow", "hmonospace",
    "hoarmenian", "hohipthai", "hohiragana", "hokatakana", "hokatakanahalfwidth", "holam",
    "holam19", "holam26", "holam32", "holamhebrew", "holamnarrowhebrew", "holamquarterhebrew",
    "holamwidehebrew", "honokhukthai", "hookabovecomb", "hookcmb", "hookpalatalizedbelowcmb",
    "hookretroflexbelowcmb", "hoonsquare", "horicoptic", "horizontalbar", "horncmb", "hotsprings",
    "house", "hparen", "hsuperior", "hturned", "huhiragana", "huiitosquare", "hukatakana",
    "hukatakanahalfwidth", "hungarumlaut", "hungarumlautcmb", "hv", "hyphen", "hypheninferior",
    "hyphenmonospace", "hyphensmall", "hyphensuperior", "hyphentwo", "i", "iacute", "iacyrillic",
    "ibengali", "ibopomofo", "ibreve", "icaron", "icircle", "icircumflex", "icyrillic", "idblgrave",
    "ideographearthcircle", "ideographfirecircle", "ideographicallianceparen",
    "ideographiccallparen", "ideographiccentrecircle", "ideographicclose", "ideographiccomma",
    "ideographiccommaleft", "ideographiccongratulationparen", "ideographiccorrectcircle",
    "ideographicearthparen", "ideographicenterpriseparen", "ideographicexcellentcircle",
    "ideographicfestivalparen", "ideographicfinancialcircle", "ideographicfinancialparen",
    "ideographicfireparen", "ideographichaveparen", "ideographichighcircle",
    "ideographiciterationmark", "ideographiclaborcircle", "ideographiclaborparen",
    "ideographicleftcircle", "ideographiclowcircle", "ideographicmedicinecircle",
    "ideographicmetalparen", "ideographicmoonparen", "ideographicnameparen", "ideographicperiod",
    "ideographicprintcircle", "ideographicreachparen", "ideographicrepresentparen",
    "ideographicresourceparen", "ideographicrightcircle", "ideographicsecretcircle",
    "ideographicselfparen", "ideographicsocietyparen", "ideographicspace",
    "ideographicspecialparen", "ideographicstockparen", "ideographicstudyparen",
    "ideographicsunparen", "ideographicsuperviseparen", "ideographicwaterparen",
    "ideographicwoodparen", "ideographiczero", "ideographmetalcircle", "ideographmooncircle",
    "ideographnamecircle", "ideographsuncircle", "ideographwatercircle", "ideographwoodcircle",
    "ideva", "idieresis", "idieresisacute", "idieresiscyrillic", "idotbelow", "iebrevecyrillic",
    "iecyrillic", "ieungacirclekorean", "ieungaparenkorean", "ieungcirclekorean", "ieungkorean",
    "ieungparenkorean", "igrave", "igujarati", "igurmukhi", "ihiragana", "ihookabove", "iibengali",
    "iicyrillic", "iideva", "iigujarati", "iigurmukhi", "iimatragurmukhi", "iinvertedbreve",
    "iishortcyrillic", "iivowelsignbengali", "iivowelsigndeva", "iivowelsigngujarati", "ij",
    "ikatakana", "ikatakanahalfwidth", "ikorean", "ilde", "iluyhebrew", "imacron",
    "imacroncyrillic", "imageorapproximatelyequal", "imatragurmukhi", "imonospace", "increment",
    "infinity", "iniarmenian", "integral", "integralbottom", "integralbt", "integralex",
    "integraltop", "integraltp", "intersection", "intisquare", "invbullet", "invcircle",
    "invsmileface", "iocyrillic", "iogonek", "iota", "iotadieresis", "iotadieresistonos",
    "iotalatin", "iotatonos", "iparen", "irigurmukhi", "ismallhiragana", "ismallkatakana",
    "ismallkatakanahalfwidth", "issharbengali", "istroke", "isuperior", "iterationhiragana",
    "iterationkatakana", "itilde", "itildebelow", "iubopomofo", "iucyrillic", "ivowelsignbengali",
    "ivowelsigndeva", "ivowelsigngujarati", "izhitsacyrillic", "izhitsadblgravecyrillic", "j",
    "jaarmenian", "jabengali", "jadeva", "jagujarati", "jagurmukhi", "jbopomofo", "jcaron",
    "jcircle", "jcircumflex", "jcrossedtail", "jdotlessstroke", "jecyrillic", "jeemarabic",
    "jeemfinalarabic", "jeeminitialarabic", "jeemmedialarabic", "jeharabic", "jehfinalarabic",
    "jhabengali", "jhadeva", "jhagujarati", "jhagurmukhi", "jheharmenian", "jis", "jmonospace",
    "jparen", "jsuperior", "k", "kabashkircyrillic", "kabengali", "kacute", "kacyrillic",
    "kadescendercyrillic", "kadeva", "kaf", "kafarabic", "kafdagesh", "kafdageshhebrew",
    "kaffinalarabic", "kafhebrew", "kafinitialarabic", "kafmedialarabic", "kafrafehebrew",
    "kagujarati", "kagurmukhi", "kahiragana", "kahookcyrillic", "kakatakana", "kakatakanahalfwidth",
    "kappa", "kappasymbolgreek", "kapyeounmieumkorean", "kapyeounphieuphkorean",
    "kapyeounpieupkorean", "kapyeounssangpieupkorean", "karoriisquare", "kashidaautoarabic",
    "kashidaautonosidebearingarabic", "kasmallkatakana", "kasquare", "kasraarabic",
    "kasratanarabic", "kastrokecyrillic", "katahiraprolongmarkhalfwidth",
    "kaverticalstrokecyrillic", "kbopomofo", "kcalsquare", "kcaron", "kcedilla", "kcircle",
    "kcommaaccent", "kdotbelow", "keharmenian", "kehiragana", "kekatakana", "kekatakanahalfwidth",
    "kenarmenian", "kesmallkatakana", "kgreenlandic", "khabengali", "khacyrillic", "khadeva",
    "khagujarati", "khagurmukhi", "khaharabic", "khahfinalarabic", "khahinitialarabic",
    "khahmedialarabic", "kheicoptic", "khhadeva", "khhagurmukhi", "khieukhacirclekorean",
    "khieukhaparenkorean", "khieukhcirclekorean", "khieukhkorean", "khieukhparenkorean",
    "khokhaithai", "khokhonthai", "khokhuatthai", "khokhwaithai", "khomutthai", "khook",
    "khorakhangthai", "khzsquare", "kihiragana", "kikatakana", "kikatakanahalfwidth",
    "kiroguramusquare", "kiromeetorusquare", "kirosquare", "kiyeokacirclekorean",
    "kiyeokaparenkorean", "kiyeokcirclekorean", "kiyeokkorean", "kiyeokparenkorean",
    "kiyeoksioskorean", "kjecyrillic", "klinebelow", "klsquare", "kmcubedsquare", "kmonospace",
    "kmsquaredsquare", "kohiragana", "kohmsquare", "kokaithai", "kokatakana", "kokatakanahalfwidth",
    "kooposquare", "koppacyrillic", "koreanstandardsymbol", "koroniscmb", "kparen", "kpasquare",
    "ksicyrillic", "ktsquare", "kturned", "kuhiragana", "kukatakana", "kukatakanahalfwidth",
    "kvsquare", "kwsquare", "l", "labengali", "lacute", "ladeva", "lagujarati", "lagurmukhi",
    "lakkhangyaothai", "lamaleffinalarabic", "lamalefhamzaabovefinalarabic",
    "lamalefhamzaaboveisolatedarabic", "lamalefhamzabelowfinalarabic",
    "lamalefhamzabelowisolatedarabic", "lamalefisolatedarabic", "lamalefmaddaabovefinalarabic",
    "lamalefmaddaaboveisolatedarabic", "lamarabic", "lambda", "lambdastroke", "lamed",
    "lameddagesh", "lameddageshhebrew", "lamedhebrew", "lamedholam", "lamedholamdagesh",
    "lamedholamdageshhebrew", "lamedholamhebrew", "lamfinalarabic", "lamhahinitialarabic",
    "laminitialarabic", "lamjeeminitialarabic", "lamkhahinitialarabic", "lamlamhehisolatedarabic",
    "lammedialarabic", "lammeemhahinitialarabic", "lammeeminitialarabic",
    "lammeemjeeminitialarabic", "lammeemkhahinitialarabic", "largecircle", "lbar", "lbelt",
    "lbopomofo", "lcaron", "lcedilla", "lcircle", "lcircumflexbelow", "lcommaaccent", "ldot",
    "ldotaccent", "ldotbelow", "ldotbelowmacron", "leftangleabovecmb", "lefttackbelowcmb", "less",
    "lessequal", "lessequalorgreater", "lessmonospace", "lessorequivalent", "lessorgreater",
    "lessoverequal", "lesssmall", "lezh", "lfblock", "lhookretroflex", "lira", "liwnarmenian", "lj",
    "ljecyrillic", "ll", "lladeva", "llagujarati", "llinebelow", "llladeva", "llvocalicbengali",
    "llvocalicdeva", "llvocalicvowelsignbengali", "llvocalicvowelsigndeva", "lmiddletilde",
    "lmonospace", "lmsquare", "lochulathai", "logicaland", "logicalnot", "logicalnotreversed",
    "logicalor", "lolingthai", "longs", "lowlinecenterline", "lowlinecmb", "lowlinedashed",
    "lozenge", "lparen", "lslash", "lsquare", "lsuperior", "ltshade", "luthai", "lvocalicbengali",
    "lvocalicdeva", "lvocalicvowelsignbengali", "lvocalicvowelsigndeva", "lxsquare", "m",
    "mabengali", "macron", "macronbelowcmb", "macroncmb", "macronlowmod", "macronmonospace",
    "macute", "madeva", "magujarati", "magurmukhi", "mahapakhhebrew", "mahapakhlefthebrew",
    "mahiragana", "maichattawalowleftthai", "maichattawalowrightthai", "maichattawathai",
    "maichattawaupperleftthai", "maieklowleftthai", "maieklowrightthai", "maiekthai",
    "maiekupperleftthai", "maihanakatleftthai", "maihanakatthai", "maitaikhuleftthai",
    "maitaikhuthai", "maitholowleftthai", "maitholowrightthai", "maithothai", "maithoupperleftthai",
    "maitrilowleftthai", "maitrilowrightthai", "maitrithai", "maitriupperleftthai", "maiyamokthai",
    "makatakana", "makatakanahalfwidth", "male", "mansyonsquare", "maqafhebrew", "mars",
    "masoracirclehebrew", "masquare", "mbopomofo", "mbsquare", "mcircle", "mcubedsquare",
    "mdotaccent", "mdotbelow", "meemarabic", "meemfinalarabic", "meeminitialarabic",
    "meemmedialarabic", "meemmeeminitialarabic", "meemmeemisolatedarabic", "meetorusquare",
    "mehiragana", "meizierasquare", "mekatakana", "mekatakanahalfwidth", "mem", "memdagesh",
    "memdageshhebrew", "memhebrew", "menarmenian", "merkhahebrew", "merkhakefulahebrew",
    "merkhakefulalefthebrew", "merkhalefthebrew", "mhook", "mhzsquare",
    "middledotkatakanahalfwidth", "middot", "mieumacirclekorean", "mieumaparenkorean",
    "mieumcirclekorean", "mieumkorean", "mieumpansioskorean", "mieumparenkorean",
    "mieumpieupkorean", "mieumsioskorean", "mihiragana", "mikatakana", "mikatakanahalfwidth",
    "minus", "minusbelowcmb", "minuscircle", "minusmod", "minusplus", "minute", "miribaarusquare",
    "mirisquare", "mlonglegturned", "mlsquare", "mmcubedsquare", "mmonospace", "mmsquaredsquare",
    "mohiragana", "mohmsquare", "mokatakana", "mokatakanahalfwidth", "molsquare", "momathai",
    "moverssquare", "moverssquaredsquare", "mparen", "mpasquare", "mssquare", "msuperior",
    "mturned", "mu", "mu1", "muasquare", "muchgreater", "muchless", "mufsquare", "mugreek",
    "mugsquare", "muhiragana", "mukatakana", "mukatakanahalfwidth", "mulsquare", "multiply",
    "mumsquare", "munahhebrew", "munahlefthebrew", "musicalnote", "musicalnotedbl", "musicflatsign",
    "musicsharpsign", "mussquare", "muvsquare", "muwsquare", "mvmegasquare", "mvsquare",
    "mwmegasquare", "mwsquare", "n", "nabengali", "nabla", "nacute", "nadeva", "nagujarati",
    "nagurmukhi", "nahiragana", "nakatakana", "nakatakanahalfwidth", "napostrophe", "nasquare",
    "nbopomofo", "nbspace", "ncaron", "ncedilla", "ncircle", "ncircumflexbelow", "ncommaaccent",
    "ndotaccent", "ndotbelow", "nehiragana", "nekatakana", "nekatakanahalfwidth", "newsheqelsign",
    "nfsquare", "ngabengali", "ngadeva", "ngagujarati", "ngagurmukhi", "ngonguthai", "nhiragana",
    "nhookleft", "nhookretroflex", "nieunacirclekorean", "nieunaparenkorean", "nieuncieuckorean",
    "nieuncirclekorean", "nieunhieuhkorean", "nieunkorean", "nieunpansioskorean",
    "nieunparenkorean", "nieunsioskorean", "nieuntikeutkorean", "nihiragana", "nikatakana",
    "nikatakanahalfwidth", "nikhahitleftthai", "nikhahitthai", "nine", "ninearabic", "ninebengali",
    "ninecircle", "ninecircleinversesansserif", "ninedeva", "ninegujarati", "ninegurmukhi",
    "ninehackarabic", "ninehangzhou", "nineideographicparen", "nineinferior", "ninemonospace",
    "nineoldstyle", "nineparen", "nineperiod", "ninepersian", "nineroman", "ninesuperior",
    "nineteencircle", "nineteenparen", "nineteenperiod", "ninethai", "nj", "njecyrillic",
    "nkatakana", "nkatakanahalfwidth", "nlegrightlong", "nlinebelow", "nmonospace", "nmsquare",
    "nnabengali", "nnadeva", "nnagujarati", "nnagurmukhi", "nnnadeva", "nohiragana", "nokatakana",
    "nokatakanahalfwidth", "nonbreakingspace", "nonenthai", "nonuthai", "noonarabic",
    "noonfinalarabic", "noonghunnaarabic", "noonghunnafinalarabic", "noonhehinitialarabic",
    "nooninitialarabic", "noonjeeminitialarabic", "noonjeemisolatedarabic", "noonmedialarabic",
    "noonmeeminitialarabic", "noonmeemisolatedarabic", "noonnoonfinalarabic", "notcontains",
    "notelement", "notelementof", "notequal", "notgreater", "notgreaternorequal",
    "notgreaternorless", "notidentical", "notless", "notlessnorequal", "notparallel", "notprecedes",
    "notsubset", "notsucceeds", "notsuperset", "nowarmenian", "nparen", "nssquare", "nsuperior",
    "ntilde", "nu", "nuhiragana", "nukatakana", "nukatakanahalfwidth", "nuktabengali", "nuktadeva",
    "nuktagujarati", "nuktagurmukhi", "numbersign", "numbersignmonospace", "numbersignsmall",
    "numeralsigngreek", "numeralsignlowergreek", "numero", "nun", "nundagesh", "nundageshhebrew",
    "nunhebrew", "nvsquare", "nwsquare", "nyabengali", "nyadeva", "nyagujarati", "nyagurmukhi", "o",
    "oacute", "oangthai", "obarred", "obarredcyrillic", "obarreddieresiscyrillic", "obengali",
    "obopomofo", "obreve", "ocandradeva", "ocandragujarati", "ocandravowelsigndeva",
    "ocandravowelsigngujarati", "ocaron", "ocircle", "ocircumflex", "ocircumflexacute",
    "ocircumflexdotbelow", "ocircumflexgrave", "ocircumflexhookabove", "ocircumflextilde",
    "ocyrillic", "odblacute", "odblgrave", "odeva", "odieresis", "odieresiscyrillic", "odotbelow",
    "oe", "oekorean", "ogonek", "ogonekcmb", "ograve", "ogujarati", "oharmenian", "ohiragana",
    "ohookabove", "ohorn", "ohornacute", "ohorndotbelow", "ohorngrave", "ohornhookabove",
    "ohorntilde", "ohungarumlaut", "oi", "oinvertedbreve", "okatakana", "okatakanahalfwidth",
    "okorean", "olehebrew", "omacron", "omacronacute", "omacrongrave", "omdeva", "omega", "omega1",
    "omegacyrillic", "omegalatinclosed", "omegaroundcyrillic", "omegatitlocyrillic", "omegatonos",
    "omgujarati", "omicron", "omicrontonos", "omonospace", "one", "onearabic", "onebengali",
    "onecircle", "onecircleinversesansserif", "onedeva", "onedotenleader", "oneeighth", "onefitted",
    "onegujarati", "onegurmukhi", "onehackarabic", "onehalf", "onehangzhou", "oneideographicparen",
    "oneinferior", "onemonospace", "onenumeratorbengali", "oneoldstyle", "oneparen", "oneperiod",
    "onepersian", "onequarter", "oneroman", "onesuperior", "onethai", "onethird", "oogonek",
    "oogonekmacron", "oogurmukhi", "oomatragurmukhi", "oopen", "oparen", "openbullet", "option",
    "ordfeminine", "ordmasculine", "orthogonal", "oshortdeva", "oshortvowelsigndeva", "oslash",
    "oslashacute", "osmallhiragana", "osmallkatakana", "osmallkatakanahalfwidth", "ostrokeacute",
    "osuperior", "otcyrillic", "otilde", "otildeacute", "otildedieresis", "oubopomofo", "overline",
    "overlinecenterline", "overlinecmb", "overlinedashed", "overlinedblwavy", "overlinewavy",
    "overscore", "ovowelsignbengali", "ovowelsigndeva", "ovowelsigngujarati", "p", "paampssquare",
    "paasentosquare", "pabengali", "pacute", "padeva", "pagedown", "pageup", "pagujarati",
    "pagurmukhi", "pahiragana", "paiyannoithai", "pakatakana", "palatalizationcyrilliccmb",
    "palochkacyrillic", "pansioskorean", "paragraph", "parallel", "parenleft",
    "parenleftaltonearabic", "parenleftbt", "parenleftex", "parenleftinferior",
    "parenleftmonospace", "parenleftsmall", "parenleftsuperior", "parenlefttp", "parenleftvertical",
    "parenright", "parenrightaltonearabic", "parenrightbt", "parenrightex", "parenrightinferior",
    "parenrightmonospace", "parenrightsmall", "parenrightsuperior", "parenrighttp",
    "parenrightvertical", "partialdiff", "paseqhebrew", "pashtahebrew", "pasquare", "patah",
    "patah11", "patah1d", "patah2a", "patahhebrew", "patahnarrowhebrew", "patahquarterhebrew",
    "patahwidehebrew", "pazerhebrew", "pbopomofo", "pcircle", "pdotaccent", "pe", "pecyrillic",
    "pedagesh", "pedageshhebrew", "peezisquare", "pefinaldageshhebrew", "peharabic", "peharmenian",
    "pehebrew", "pehfinalarabic", "pehinitialarabic", "pehiragana", "pehmedialarabic", "pekatakana",
    "pemiddlehookcyrillic", "perafehebrew", "percent", "percentarabic", "percentmonospace",
    "percentsmall", "period", "periodarmenian", "periodcentered", "periodhalfwidth",
    "periodinferior", "periodmonospace", "periodsmall", "periodsuperior", "perispomenigreekcmb",
    "perpendicular", "perthousand", "peseta", "pfsquare", "phabengali", "phadeva", "phagujarati",
    "phagurmukhi", "phi", "phi1", "phieuphacirclekorean", "phieuphaparenkorean",
    "phieuphcirclekorean", "phieuphkorean", "phieuphparenkorean", "philatin", "phinthuthai",
    "phisymbolgreek", "phook", "phophanthai", "phophungthai", "phosamphaothai", "pi",
    "pieupacirclekorean", "pieupaparenkorean", "pieupcieuckorean", "pieupcirclekorean",
    "pieupkiyeokkorean", "pieupkorean", "pieupparenkorean", "pieupsioskiyeokkorean",
    "pieupsioskorean", "pieupsiostikeutkorean", "pieupthieuthkorean", "pieuptikeutkorean",
    "pihiragana", "pikatakana", "pisymbolgreek", "piwrarmenian", "plus", "plusbelowcmb",
    "pluscircle", "plusminus", "plusmod", "plusmonospace", "plussmall", "plussuperior",
    "pmonospace", "pmsquare", "pohiragana", "pointingindexdownwhite", "pointingindexleftwhite",
    "pointingindexrightwhite", "pointingindexupwhite", "pokatakana", "poplathai", "postalmark",
    "postalmarkface", "pparen", "precedes", "prescription", "primemod", "primereversed", "product",
    "projective", "prolongedkana", "propellor", "propersubset", "propersuperset", "proportion",
    "proportional", "psi", "psicyrillic", "psilipneumatacyrilliccmb", "pssquare", "puhiragana",
    "pukatakana", "pvsquare", "pwsquare", "q", "qadeva", "qadmahebrew", "qafarabic",
    "qaffinalarabic", "qafinitialarabic", "qafmedialarabic", "qamats", "qamats10", "qamats1a",
    "qamats1c", "qamats27", "qamats29", "qamats33", "qamatsde", "qamatshebrew",
    "qamatsnarrowhebrew", "qamatsqatanhebrew", "qamatsqatannarrowhebrew",
    "qamatsqatanquarterhebrew", "qamatsqatanwidehebrew", "qamatsquarterhebrew", "qamatswidehebrew",
    "qarneyparahebrew", "qbopomofo", "qcircle", "qhook", "qmonospace", "qof", "qofdagesh",
    "qofdageshhebrew", "qofhatafpatah", "qofhatafpatahhebrew", "qofhatafsegol",
    "qofhatafsegolhebrew", "qofhebrew", "qofhiriq", "qofhiriqhebrew", "qofholam", "qofholamhebrew",
    "qofpatah", "qofpatahhebrew", "qofqamats", "qofqamatshebrew", "qofqubuts", "qofqubutshebrew",
    "qofsegol", "qofsegolhebrew", "qofsheva", "qofshevahebrew", "qoftsere", "qoftserehebrew",
    "qparen", "quarternote", "qubuts", "qubuts18", "qubuts25", "qubuts31", "qubutshebrew",
    "qubutsnarrowhebrew", "qubutsquarterhebrew", "qubutswidehebrew", "question", "questionarabic",
    "questionarmenian", "questiondown", "questiondownsmall", "questiongreek", "questionmonospace",
    "questionsmall", "quotedbl", "quotedblbase", "quotedblleft", "quotedblmonospace",
    "quotedblprime", "quotedblprimereversed", "quotedblright", "quoteleft", "quoteleftreversed",
    "quotereversed", "quoteright", "quoterightn", "quotesinglbase", "quotesingle",
    "quotesinglemonospace", "r", "raarmenian", "rabengali", "racute", "radeva", "radical",
    "radicalex", "radoverssquare", "radoverssquaredsquare", "radsquare", "rafe", "rafehebrew",
    "ragujarati", "ragurmukhi", "rahiragana", "rakatakana", "rakatakanahalfwidth",
    "ralowerdiagonalbengali", "ramiddlediagonalbengali", "ramshorn", "ratio", "rbopomofo", "rcaron",
    "rcedilla", "rcircle", "rcommaaccent", "rdblgrave", "rdotaccent", "rdotbelow",
    "rdotbelowmacron", "referencemark", "reflexsubset", "reflexsuperset", "registered",
    "registersans", "registerserif", "reharabic", "reharmenian", "rehfinalarabic", "rehiragana",
    "rehyehaleflamarabic", "rekatakana", "rekatakanahalfwidth", "resh", "reshdageshhebrew",
    "reshhatafpatah", "reshhatafpatahhebrew", "reshhatafsegol", "reshhatafsegolhebrew",
    "reshhebrew", "reshhiriq", "reshhiriqhebrew", "reshholam", "reshholamhebrew", "reshpatah",
    "reshpatahhebrew", "reshqamats", "reshqamatshebrew", "reshqubuts", "reshqubutshebrew",
    "reshsegol", "reshsegolhebrew", "reshsheva", "reshshevahebrew", "reshtsere", "reshtserehebrew",
    "reversedtilde", "reviahebrew", "reviamugrashhebrew", "revlogicalnot", "rfishhook",
    "rfishhookreversed", "rhabengali", "rhadeva", "rho", "rhook", "rhookturned",
    "rhookturnedsuperior", "rhosymbolgreek", "rhotichookmod", "rieulacirclekorean",
    "rieulaparenkorean", "rieulcirclekorean", "rieulhieuhkorean", "rieulkiyeokkorean",
    "rieulkiyeoksioskorean", "rieulkorean", "rieulmieumkorean", "rieulpansioskorean",
    "rieulparenkorean", "rieulphieuphkorean", "rieulpieupkorean", "rieulpieupsioskorean",
    "rieulsioskorean", "rieulthieuthkorean", "rieultikeutkorean", "rieulyeorinhieuhkorean",
    "rightangle", "righttackbelowcmb", "righttriangle", "rihiragana", "rikatakana",
    "rikatakanahalfwidth", "ring", "ringbelowcmb", "ringcmb", "ringhalfleft",
    "ringhalfleftarmenian", "ringhalfleftbelowcmb", "ringhalfleftcentered", "ringhalfright",
    "ringhalfrightbelowcmb", "ringhalfrightcentered", "rinvertedbreve", "rittorusquare",
    "rlinebelow", "rlongleg", "rlonglegturned", "rmonospace", "rohiragana", "rokatakana",
    "rokatakanahalfwidth", "roruathai", "rparen", "rrabengali", "rradeva", "rragurmukhi",
    "rreharabic", "rrehfinalarabic", "rrvocalicbengali", "rrvocalicdeva", "rrvocalicgujarati",
    "rrvocalicvowelsignbengali", "rrvocalicvowelsigndeva", "rrvocalicvowelsigngujarati",
    "rsuperior", "rtblock", "rturned", "rturnedsuperior", "ruhiragana", "rukatakana",
    "rukatakanahalfwidth", "rupeemarkbengali", "rupeesignbengali", "rupiah", "ruthai",
    "rvocalicbengali", "rvocalicdeva", "rvocalicgujarati", "rvocalicvowelsignbengali",
    "rvocalicvowelsigndeva", "rvocalicvowelsigngujarati", "s", "sabengali", "sacute",
    "sacutedotaccent", "sadarabic", "sadeva", "sadfinalarabic", "sadinitialarabic",
    "sadmedialarabic", "sagujarati", "sagurmukhi", "sahiragana", "sakatakana",
    "sakatakanahalfwidth", "sallallahoualayhewasallamarabic", "samekh", "samekhdagesh",
    "samekhdageshhebrew", "samekhhebrew", "saraaathai", "saraaethai", "saraaimaimalaithai",
    "saraaimaimuanthai", "saraamthai", "saraathai", "saraethai", "saraiileftthai", "saraiithai",
    "saraileftthai", "saraithai", "saraothai", "saraueeleftthai", "saraueethai", "saraueleftthai",
    "sarauethai", "sarauthai", "sarauuthai", "sbopomofo", "scaron", "scarondotaccent", "scedilla",
    "schwa", "schwacyrillic", "schwadieresiscyrillic", "schwahook", "scircle", "scircumflex",
    "scommaaccent", "sdotaccent", "sdotbelow", "sdotbelowdotaccent", "seagullbelowcmb", "second",
    "secondtonechinese", "section", "seenarabic", "seenfinalarabic", "seeninitialarabic",
    "seenmedialarabic", "segol", "segol13", "segol1f", "segol2c", "segolhebrew",
    "segolnarrowhebrew", "segolquarterhebrew", "segoltahebrew", "segolwidehebrew", "seharmenian",
    "sehiragana", "sekatakana", "sekatakanahalfwidth", "semicolon", "semicolonarabic",
    "semicolonmonospace", "semicolonsmall", "semivoicedmarkkana", "semivoicedmarkkanahalfwidth",
    "sentisquare", "sentosquare", "seven", "sevenarabic", "sevenbengali", "sevencircle",
    "sevencircleinversesansserif", "sevendeva", "seveneighths", "sevengujarati", "sevengurmukhi",
    "sevenhackarabic", "sevenhangzhou", "sevenideographicparen", "seveninferior", "sevenmonospace",
    "sevenoldstyle", "sevenparen", "sevenperiod", "sevenpersian", "sevenroman", "sevensuperior",
    "seventeencircle", "seventeenparen", "seventeenperiod", "seventhai", "sfthyphen", "shaarmenian",
    "shabengali", "shacyrillic", "shaddaarabic", "shaddadammaarabic", "shaddadammatanarabic",
    "shaddafathaarabic", "shaddafathatanarabic", "shaddakasraarabic", "shaddakasratanarabic",
    "shade", "shadedark", "shadelight", "shademedium", "shadeva", "shagujarati", "shagurmukhi",
    "shalshelethebrew", "shbopomofo", "shchacyrillic", "sheenarabic", "sheenfinalarabic",
    "sheeninitialarabic", "sheenmedialarabic", "sheicoptic", "sheqel", "sheqelhebrew", "sheva",
    "sheva115", "sheva15", "sheva22", "sheva2e", "shevahebrew", "shevanarrowhebrew",
    "shevaquarterhebrew", "shevawidehebrew", "shhacyrillic", "shimacoptic", "shin", "shindagesh",
    "shindageshhebrew", "shindageshshindot", "shindageshshindothebrew", "shindageshsindot",
    "shindageshsindothebrew", "shindothebrew", "shinhebrew", "shinshindot", "shinshindothebrew",
    "shinsindot", "shinsindothebrew", "shook", "sigma", "sigma1", "sigmafinal",
    "sigmalunatesymbolgreek", "sihiragana", "sikatakana", "sikatakanahalfwidth", "siluqhebrew",
    "siluqlefthebrew", "similar", "sindothebrew", "siosacirclekorean", "siosaparenkorean",
    "sioscieuckorean", "sioscirclekorean", "sioskiyeokkorean", "sioskorean", "siosnieunkorean",
    "siosparenkorean", "siospieupkorean", "siostikeutkorean", "six", "sixarabic", "sixbengali",
    "sixcircle", "sixcircleinversesansserif", "sixdeva", "sixgujarati", "sixgurmukhi",
    "sixhackarabic", "sixhangzhou", "sixideographicparen", "sixinferior", "sixmonospace",
    "sixoldstyle", "sixparen", "sixperiod", "sixpersian", "sixroman", "sixsuperior",
    "sixteencircle", "sixteencurrencydenominatorbengali", "sixteenparen", "sixteenperiod",
    "sixthai", "slash", "slashmonospace", "slong", "slongdotaccent", "smileface", "smonospace",
    "sofpasuqhebrew", "softhyphen", "softsigncyrillic", "sohiragana", "sokatakana",
    "sokatakanahalfwidth", "soliduslongoverlaycmb", "solidusshortoverlaycmb", "sorusithai",
    "sosalathai", "sosothai", "sosuathai", "space", "spacehackarabic", "spade", "spadesuitblack",
    "spadesuitwhite", "sparen", "squarebelowcmb", "squarecc", "squarecm",
    "squarediagonalcrosshatchfill", "squarehorizontalfill", "squarekg", "squarekm",
    "squarekmcapital", "squareln", "squarelog", "squaremg", "squaremil", "squaremm",
    "squaremsquared", "squareorthogonalcrosshatchfill", "squareupperlefttolowerrightfill",
    "squareupperrighttolowerleftfill", "squareverticalfill", "squarewhitewithsmallblack",
    "srsquare", "ssabengali", "ssadeva", "ssagujarati", "ssangcieuckorean", "ssanghieuhkorean",
    "ssangieungkorean", "ssangkiyeokkorean", "ssangnieunkorean", "ssangpieupkorean",
    "ssangsioskorean", "ssangtikeutkorean", "ssuperior", "sterling", "sterlingmonospace",
    "strokelongoverlaycmb", "strokeshortoverlaycmb", "subset", "subsetnotequal", "subsetorequal",
    "succeeds", "suchthat", "suhiragana", "sukatakana", "sukatakanahalfwidth", "sukunarabic",
    "summation", "sun", "superset", "supersetnotequal", "supersetorequal", "svsquare",
    "syouwaerasquare", "t", "tabengali", "tackdown", "tackleft", "tadeva", "tagujarati",
    "tagurmukhi", "taharabic", "tahfinalarabic", "tahinitialarabic", "tahiragana",
    "tahmedialarabic", "taisyouerasquare", "takatakana", "takatakanahalfwidth", "tatweelarabic",
    "tau", "tav", "tavdages", "tavdagesh", "tavdageshhebrew", "tavhebrew", "tbar", "tbopomofo",
    "tcaron", "tccurl", "tcedilla", "tcheharabic", "tchehfinalarabic", "tchehinitialarabic",
    "tchehmedialarabic", "tchehmeeminitialarabic", "tcircle", "tcircumflexbelow", "tcommaaccent",
    "tdieresis", "tdotaccent", "tdotbelow", "tecyrillic", "tedescendercyrillic", "teharabic",
    "tehfinalarabic", "tehhahinitialarabic", "tehhahisolatedarabic", "tehinitialarabic",
    "tehiragana", "tehjeeminitialarabic", "tehjeemisolatedarabic", "tehmarbutaarabic",
    "tehmarbutafinalarabic", "tehmedialarabic", "tehmeeminitialarabic", "tehmeemisolatedarabic",
    "tehnoonfinalarabic", "tekatakana", "tekatakanahalfwidth", "telephone", "telephoneblack",
    "telishagedolahebrew", "telishaqetanahebrew", "tencircle", "tenideographicparen", "tenparen",
    "tenperiod", "tenroman", "tesh", "tet", "tetdagesh", "tetdageshhebrew", "tethebrew",
    "tetsecyrillic", "tevirhebrew", "tevirlefthebrew", "thabengali", "thadeva", "thagujarati",
    "thagurmukhi", "thalarabic", "thalfinalarabic", "thanthakhatlowleftthai",
    "thanthakhatlowrightthai", "thanthakhatthai", "thanthakhatupperleftthai", "theharabic",
    "thehfinalarabic", "thehinitialarabic", "thehmedialarabic", "thereexists", "therefore", "theta",
    "theta1", "thetasymbolgreek", "thieuthacirclekorean", "thieuthaparenkorean",
    "thieuthcirclekorean", "thieuthkorean", "thieuthparenkorean", "thirteencircle", "thirteenparen",
    "thirteenperiod", "thonangmonthothai", "thook", "thophuthaothai", "thorn", "thothahanthai",
    "thothanthai", "thothongthai", "thothungthai", "thousandcyrillic", "thousandsseparatorarabic",
    "thousandsseparatorpersian", "three", "threearabic", "threebengali", "threecircle",
    "threecircleinversesansserif", "threedeva", "threeeighths", "threegujarati", "threegurmukhi",
    "threehackarabic", "threehangzhou", "threeideographicparen", "threeinferior", "threemonospace",
    "threenumeratorbengali", "threeoldstyle", "threeparen", "threeperiod", "threepersian",
    "threequarters", "threequartersemdash", "threeroman", "threesuperior", "threethai", "thzsquare",
    "tihiragana", "tikatakana", "tikatakanahalfwidth", "tikeutacirclekorean", "tikeutaparenkorean",
    "tikeutcirclekorean", "tikeutkorean", "tikeutparenkorean", "tilde", "tildebelowcmb", "tildecmb",
    "tildecomb", "tildedoublecmb", "tildeoperator", "tildeoverlaycmb", "tildeverticalcmb",
    "timescircle", "tipehahebrew", "tipehalefthebrew", "tippigurmukhi", "titlocyrilliccmb",
    "tiwnarmenian", "tlinebelow", "tmonospace", "toarmenian", "tohiragana", "tokatakana",
    "tokatakanahalfwidth", "tonebarextrahighmod", "tonebarextralowmod", "tonebarhighmod",
    "tonebarlowmod", "tonebarmidmod", "tonefive", "tonesix", "tonetwo", "tonos", "tonsquare",
    "topatakthai", "tortoiseshellbracketleft", "tortoiseshellbracketleftsmall",
    "tortoiseshellbracketleftvertical", "tortoiseshellbracketright",
    "tortoiseshellbracketrightsmall", "tortoiseshellbracketrightvertical", "totaothai",
    "tpalatalhook", "tparen", "trademark", "trademarksans", "trademarkserif", "tretroflexhook",
    "triagdn", "triaglf", "triagrt", "triagup", "ts", "tsadi", "tsadidagesh", "tsadidageshhebrew",
    "tsadihebrew", "tsecyrillic", "tsere", "tsere12", "tsere1e", "tsere2b", "tserehebrew",
    "tserenarrowhebrew", "tserequarterhebrew", "tserewidehebrew", "tshecyrillic", "tsuperior",
    "ttabengali", "ttadeva", "ttagujarati", "ttagurmukhi", "tteharabic", "ttehfinalarabic",
    "ttehinitialarabic", "ttehmedialarabic", "tthabengali", "tthadeva", "tthagujarati",
    "tthagurmukhi", "tturned", "tuhiragana", "tukatakana", "tukatakanahalfwidth", "tusmallhiragana",
    "tusmallkatakana", "tusmallkatakanahalfwidth", "twelvecircle", "twelveparen", "twelveperiod",
    "twelveroman", "twentycircle", "twentyhangzhou", "twentyparen", "twentyperiod", "two",
    "twoarabic", "twobengali", "twocircle", "twocircleinversesansserif", "twodeva",
    "twodotenleader", "twodotleader", "twodotleadervertical", "twogujarati", "twogurmukhi",
    "twohackarabic", "twohangzhou", "twoideographicparen", "twoinferior", "twomonospace",
    "twonumeratorbengali", "twooldstyle", "twoparen", "twoperiod", "twopersian", "tworoman",
    "twostroke", "twosuperior", "twothai", "twothirds", "u", "uacute", "ubar", "ubengali",
    "ubopomofo", "ubreve", "ucaron", "ucircle", "ucircumflex", "ucircumflexbelow", "ucyrillic",
    "udattadeva", "udblacute", "udblgrave", "udeva", "udieresis", "udieresisacute",
    "udieresisbelow", "udieresiscaron", "udieresiscyrillic", "udieresisgrave", "udieresismacron",
    "udotbelow", "ugrave", "ugujarati", "ugurmukhi", "uhiragana", "uhookabove", "uhorn",
    "uhornacute", "uhorndotbelow", "uhorngrave", "uhornhookabove", "uhorntilde", "uhungarumlaut",
    "uhungarumlautcyrillic", "uinvertedbreve", "ukatakana", "ukatakanahalfwidth", "ukcyrillic",
    "ukorean", "umacron", "umacroncyrillic", "umacrondieresis", "umatragurmukhi", "umonospace",
    "underscore", "underscoredbl", "underscoremonospace", "underscorevertical", "underscorewavy",
    "union", "universal", "uogonek", "uparen", "upblock", "upperdothebrew", "upsilon",
    "upsilondieresis", "upsilondieresistonos", "upsilonlatin", "upsilontonos", "uptackbelowcmb",
    "uptackmod", "uragurmukhi", "uring", "ushortcyrillic", "usmallhiragana", "usmallkatakana",
    "usmallkatakanahalfwidth", "ustraightcyrillic", "ustraightstrokecyrillic", "utilde",
    "utildeacute", "utildebelow", "uubengali", "uudeva", "uugujarati", "uugurmukhi",
    "uumatragurmukhi", "uuvowelsignbengali", "uuvowelsigndeva", "uuvowelsigngujarati",
    "uvowelsignbengali", "uvowelsigndeva", "uvowelsigngujarati", "v", "vadeva", "vagujarati",
    "vagurmukhi", "vakatakana", "vav", "vavdagesh", "vavdagesh65", "vavdageshhebrew", "vavhebrew",
    "vavholam", "vavholamhebrew", "vavvavhebrew", "vavyodhebrew", "vcircle", "vdotbelow",
    "vecyrillic", "veharabic", "vehfinalarabic", "vehinitialarabic", "vehmedialarabic",
    "vekatakana", "venus", "verticalbar", "verticallineabovecmb", "verticallinebelowcmb",
    "verticallinelowmod", "verticallinemod", "vewarmenian", "vhook", "vikatakana", "viramabengali",
    "viramadeva", "viramagujarati", "visargabengali", "visargadeva", "visargagujarati",
    "vmonospace", "voarmenian", "voicediterationhiragana", "voicediterationkatakana",
    "voicedmarkkana", "voicedmarkkanahalfwidth", "vokatakana", "vparen", "vtilde", "vturned",
    "vuhiragana", "vukatakana", "w", "wacute", "waekorean", "wahiragana", "wakatakana",
    "wakatakanahalfwidth", "wakorean", "wasmallhiragana", "wasmallkatakana", "wattosquare",
    "wavedash", "wavyunderscorevertical", "wawarabic", "wawfinalarabic", "wawhamzaabovearabic",
    "wawhamzaabovefinalarabic", "wbsquare", "wcircle", "wcircumflex", "wdieresis", "wdotaccent",
    "wdotbelow", "wehiragana", "weierstrass", "wekatakana", "wekorean", "weokorean", "wgrave",
    "whitebullet", "whitecircle", "whitecircleinverse", "whitecornerbracketleft",
    "whitecornerbracketleftvertical", "whitecornerbracketright", "whitecornerbracketrightvertical",
    "whitediamond", "whitediamondcontainingblacksmalldiamond", "whitedownpointingsmalltriangle",
    "whitedownpointingtriangle", "whiteleftpointingsmalltriangle", "whiteleftpointingtriangle",
    "whitelenticularbracketleft", "whitelenticularbracketright", "whiterightpointingsmalltriangle",
    "whiterightpointingtriangle", "whitesmallsquare", "whitesmilingface", "whitesquare",
    "whitestar", "whitetelephone", "whitetortoiseshellbracketleft",
    "whitetortoiseshellbracketright", "whiteuppointingsmalltriangle", "whiteuppointingtriangle",
    "wihiragana", "wikatakana", "wikorean", "wmonospace", "wohiragana", "wokatakana",
    "wokatakanahalfwidth", "won", "wonmonospace", "wowaenthai", "wparen", "wring", "wsuperior",
    "wturned", "wynn", "x", "xabovecmb", "xbopomofo", "xcircle", "xdieresis", "xdotaccent",
    "xeharmenian", "xi", "xmonospace", "xparen", "xsuperior", "y", "yaadosquare", "yabengali",
    "yacute", "yadeva", "yaekorean", "yagujarati", "yagurmukhi", "yahiragana", "yakatakana",
    "yakatakanahalfwidth", "yakorean", "yamakkanthai", "yasmallhiragana", "yasmallkatakana",
    "yasmallkatakanahalfwidth", "yatcyrillic", "ycircle", "ycircumflex", "ydieresis", "ydotaccent",
    "ydotbelow", "yeharabic", "yehbarreearabic", "yehbarreefinalarabic", "yehfinalarabic",
    "yehhamzaabovearabic", "yehhamzaabovefinalarabic", "yehhamzaaboveinitialarabic",
    "yehhamzaabovemedialarabic", "yehinitialarabic", "yehmedialarabic", "yehmeeminitialarabic",
    "yehmeemisolatedarabic", "yehnoonfinalarabic", "yehthreedotsbelowarabic", "yekorean", "yen",
    "yenmonospace", "yeokorean", "yeorinhieuhkorean", "yerahbenyomohebrew",
    "yerahbenyomolefthebrew", "yericyrillic", "yerudieresiscyrillic", "yesieungkorean",
    "yesieungpansioskorean", "yesieungsioskorean", "yetivhebrew", "ygrave", "yhook", "yhookabove",
    "yiarmenian", "yicyrillic", "yikorean", "yinyang", "yiwnarmenian", "ymonospace", "yod",
    "yoddagesh", "yoddageshhebrew", "yodhebrew", "yodyodhebrew", "yodyodpatahhebrew", "yohiragana",
    "yoikorean", "yokatakana", "yokatakanahalfwidth", "yokorean", "yosmallhiragana",
    "yosmallkatakana", "yosmallkatakanahalfwidth", "yotgreek", "yoyaekorean", "yoyakorean",
    "yoyakthai", "yoyingthai", "yparen", "ypogegrammeni", "ypogegrammenigreekcmb", "yr", "yring",
    "ysuperior", "ytilde", "yturned", "yuhiragana", "yuikorean", "yukatakana",
    "yukatakanahalfwidth", "yukorean", "yusbigcyrillic", "yusbigiotifiedcyrillic",
    "yuslittlecyrillic", "yuslittleiotifiedcyrillic", "yusmallhiragana", "yusmallkatakana",
    "yusmallkatakanahalfwidth", "yuyekorean", "yuyeokorean", "yyabengali", "yyadeva", "z",
    "zaarmenian", "zacute", "zadeva", "zagurmukhi", "zaharabic", "zahfinalarabic",
    "zahinitialarabic", "zahiragana", "zahmedialarabic", "zainarabic", "zainfinalarabic",
    "zakatakana", "zaqefgadolhebrew", "zaqefqatanhebrew", "zarqahebrew", "zayin", "zayindagesh",
    "zayindageshhebrew", "zayinhebrew", "zbopomofo", "zcaron", "zcircle", "zcircumflex", "zcurl",
    "zdot", "zdotaccent", "zdotbelow", "zecyrillic", "zedescendercyrillic", "zedieresiscyrillic",
    "zehiragana", "zekatakana", "zero", "zeroarabic", "zerobengali", "zerodeva", "zerogujarati",
    "zerogurmukhi", "zerohackarabic", "zeroinferior", "zeromonospace", "zerooldstyle",
    "zeropersian", "zerosuperior", "zerothai", "zerowidthjoiner", "zerowidthnonjoiner",
    "zerowidthspace", "zeta", "zhbopomofo", "zhearmenian", "zhebrevecyrillic", "zhecyrillic",
    "zhedescendercyrillic", "zhedieresiscyrillic", "zihiragana", "zikatakana", "zinorhebrew",
    "zlinebelow", "zmonospace", "zohiragana", "zokatakana", "zparen", "zretroflexhook", "zstroke",
    "zuhiragana", "zukatakana",
];
